name = "MayLAN Modpack"
author = "jeffors"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37a642f2a2f2f00a6300276f284a433ff818542500faf17d3029c70bef6f48d3"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
