name = "MayLAN Modpack"
author = "jeffors"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3acff981124f6beeed401da02c6e1d5fa81b269b745455ba66fe726199bea3f7"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
