name = "MayLAN Modpack"
author = "jeffors"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac89bff649c2df654bd06ab25b028eb8baddaa5fb15223bf54a20a198ede4c6e"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
